# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/user/CLionProjects/boost_server_manager

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/user/CLionProjects/boost_server_manager

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/CLionProjects/boost_server_manager/CMakeFiles /home/user/CLionProjects/boost_server_manager//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/user/CLionProjects/boost_server_manager/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named my_server

# Build rule for target.
my_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 my_server
.PHONY : my_server

# fast build rule for target.
my_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_server.dir/build.make CMakeFiles/my_server.dir/build
.PHONY : my_server/fast

#=============================================================================
# Target rules for targets named WebServer

# Build rule for target.
WebServer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 WebServer
.PHONY : WebServer

# fast build rule for target.
WebServer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/build
.PHONY : WebServer/fast

src/listener/listener.o: src/listener/listener.cpp.o
.PHONY : src/listener/listener.o

# target to build an object file
src/listener/listener.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_server.dir/build.make CMakeFiles/my_server.dir/src/listener/listener.cpp.o
.PHONY : src/listener/listener.cpp.o

src/listener/listener.i: src/listener/listener.cpp.i
.PHONY : src/listener/listener.i

# target to preprocess a source file
src/listener/listener.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_server.dir/build.make CMakeFiles/my_server.dir/src/listener/listener.cpp.i
.PHONY : src/listener/listener.cpp.i

src/listener/listener.s: src/listener/listener.cpp.s
.PHONY : src/listener/listener.s

# target to generate assembly for a file
src/listener/listener.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_server.dir/build.make CMakeFiles/my_server.dir/src/listener/listener.cpp.s
.PHONY : src/listener/listener.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/server/server.o: src/server/server.cpp.o
.PHONY : src/server/server.o

# target to build an object file
src/server/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_server.dir/build.make CMakeFiles/my_server.dir/src/server/server.cpp.o
.PHONY : src/server/server.cpp.o

src/server/server.i: src/server/server.cpp.i
.PHONY : src/server/server.i

# target to preprocess a source file
src/server/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_server.dir/build.make CMakeFiles/my_server.dir/src/server/server.cpp.i
.PHONY : src/server/server.cpp.i

src/server/server.s: src/server/server.cpp.s
.PHONY : src/server/server.s

# target to generate assembly for a file
src/server/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_server.dir/build.make CMakeFiles/my_server.dir/src/server/server.cpp.s
.PHONY : src/server/server.cpp.s

src/session/http_session.o: src/session/http_session.cpp.o
.PHONY : src/session/http_session.o

# target to build an object file
src/session/http_session.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_server.dir/build.make CMakeFiles/my_server.dir/src/session/http_session.cpp.o
.PHONY : src/session/http_session.cpp.o

src/session/http_session.i: src/session/http_session.cpp.i
.PHONY : src/session/http_session.i

# target to preprocess a source file
src/session/http_session.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_server.dir/build.make CMakeFiles/my_server.dir/src/session/http_session.cpp.i
.PHONY : src/session/http_session.cpp.i

src/session/http_session.s: src/session/http_session.cpp.s
.PHONY : src/session/http_session.s

# target to generate assembly for a file
src/session/http_session.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_server.dir/build.make CMakeFiles/my_server.dir/src/session/http_session.cpp.s
.PHONY : src/session/http_session.cpp.s

src/session/ssl/https_session.o: src/session/ssl/https_session.cpp.o
.PHONY : src/session/ssl/https_session.o

# target to build an object file
src/session/ssl/https_session.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_server.dir/build.make CMakeFiles/my_server.dir/src/session/ssl/https_session.cpp.o
.PHONY : src/session/ssl/https_session.cpp.o

src/session/ssl/https_session.i: src/session/ssl/https_session.cpp.i
.PHONY : src/session/ssl/https_session.i

# target to preprocess a source file
src/session/ssl/https_session.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_server.dir/build.make CMakeFiles/my_server.dir/src/session/ssl/https_session.cpp.i
.PHONY : src/session/ssl/https_session.cpp.i

src/session/ssl/https_session.s: src/session/ssl/https_session.cpp.s
.PHONY : src/session/ssl/https_session.s

# target to generate assembly for a file
src/session/ssl/https_session.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_server.dir/build.make CMakeFiles/my_server.dir/src/session/ssl/https_session.cpp.s
.PHONY : src/session/ssl/https_session.cpp.s

src/session/ssl/wss_session.o: src/session/ssl/wss_session.cpp.o
.PHONY : src/session/ssl/wss_session.o

# target to build an object file
src/session/ssl/wss_session.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_server.dir/build.make CMakeFiles/my_server.dir/src/session/ssl/wss_session.cpp.o
.PHONY : src/session/ssl/wss_session.cpp.o

src/session/ssl/wss_session.i: src/session/ssl/wss_session.cpp.i
.PHONY : src/session/ssl/wss_session.i

# target to preprocess a source file
src/session/ssl/wss_session.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_server.dir/build.make CMakeFiles/my_server.dir/src/session/ssl/wss_session.cpp.i
.PHONY : src/session/ssl/wss_session.cpp.i

src/session/ssl/wss_session.s: src/session/ssl/wss_session.cpp.s
.PHONY : src/session/ssl/wss_session.s

# target to generate assembly for a file
src/session/ssl/wss_session.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_server.dir/build.make CMakeFiles/my_server.dir/src/session/ssl/wss_session.cpp.s
.PHONY : src/session/ssl/wss_session.cpp.s

src/session/ws_session.o: src/session/ws_session.cpp.o
.PHONY : src/session/ws_session.o

# target to build an object file
src/session/ws_session.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_server.dir/build.make CMakeFiles/my_server.dir/src/session/ws_session.cpp.o
.PHONY : src/session/ws_session.cpp.o

src/session/ws_session.i: src/session/ws_session.cpp.i
.PHONY : src/session/ws_session.i

# target to preprocess a source file
src/session/ws_session.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_server.dir/build.make CMakeFiles/my_server.dir/src/session/ws_session.cpp.i
.PHONY : src/session/ws_session.cpp.i

src/session/ws_session.s: src/session/ws_session.cpp.s
.PHONY : src/session/ws_session.s

# target to generate assembly for a file
src/session/ws_session.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/my_server.dir/build.make CMakeFiles/my_server.dir/src/session/ws_session.cpp.s
.PHONY : src/session/ws_session.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... WebServer"
	@echo "... my_server"
	@echo "... src/listener/listener.o"
	@echo "... src/listener/listener.i"
	@echo "... src/listener/listener.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/server/server.o"
	@echo "... src/server/server.i"
	@echo "... src/server/server.s"
	@echo "... src/session/http_session.o"
	@echo "... src/session/http_session.i"
	@echo "... src/session/http_session.s"
	@echo "... src/session/ssl/https_session.o"
	@echo "... src/session/ssl/https_session.i"
	@echo "... src/session/ssl/https_session.s"
	@echo "... src/session/ssl/wss_session.o"
	@echo "... src/session/ssl/wss_session.i"
	@echo "... src/session/ssl/wss_session.s"
	@echo "... src/session/ws_session.o"
	@echo "... src/session/ws_session.i"
	@echo "... src/session/ws_session.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

